# Generated by Django 4.1.3 on 2022-11-12 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=15, unique=True)),
                ('bio', models.TextField(blank=True, max_length=160, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_img', models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_images/')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('website', models.URLField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('no_of_followers', models.IntegerField(default=0)),
                ('no_of_posts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
