# Generated by Django 4.1.3 on 2022-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0002_alter_profile_name_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_img',
            field=models.ImageField(blank=True, default='default-bg.jpeg', null=True, upload_to='banner_images/'),
        ),
    ]
