# Generated by Django 4.1.3 on 2022-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_reply_name_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='og_post',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
