# Generated by Django 4.1.3 on 2022-11-15 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_reply_reply_id_alter_post_image_alter_reply_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_posts.post'),
        ),
    ]
