# Generated by Django 4.1.3 on 2022-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0005_post_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
