# Generated by Django 4.1.3 on 2022-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0006_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_img',
            field=models.CharField(blank=True, default='blank-profile-picture.png', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='profile_img',
            field=models.CharField(blank=True, default='blank-profile-picture.png', max_length=300, null=True),
        ),
    ]
