# Generated by Django 4.1.3 on 2022-11-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0007_post_profile_img_reply_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_img',
            field=models.CharField(default='blank-profile-picture.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='reply',
            name='profile_img',
            field=models.CharField(default='blank-profile-picture.png', max_length=300),
        ),
    ]
